str = """dshgsdlgsjdhglsdkjghdsvhoewihcdsgsdhlkghsdlgiwurghwrfbsldgkjsbgwrtugwpigbsldkgjdslgkdgl
        slfgkhslgusowiweuceouircnowefpweohwepoihfcnwepofcewncwpoirucenwfcpeoifcnewpofihewncpefo
        dshgsdlgsjdhglsdkjghdsvhoewihcdsgsdhlkghsdlgiwurghwrfbsldgkjsbgwrtugwpigbsldkgjdslgkdgl
        slfgkhslgusowiweuceouircnowefpweohwepoihfcnwepofcewncwpoirucenwfcpeoifcnewpofihewncpefo
        dshgsdlgsjdhglsdkjghdsvhoewihcdsgsdhlkghsdlgiwurghwrfbsldgkjsbgwrtugwpigbsldkgjdslgkdgl
        slfgkhslgusowiweuceouircnowefpweohwepoihfcnutfcewncwpoirucenwfcpeoifcnewpofihewncpefo
        dshgsdlgsjdhglsdkjghdsvhoewihcdsgsdhlkghsdlgiwurghwrfbsldgkjsbgwrtugwpigbsldkgjdslgkdgl
        slfgkhslgusowiweuceouircnowefpweohwepoihfcnwepofcewncwpoirucenwfcpeoifcnewpofihewncpefo
        dshgsdlgsjdhglsdkjghdsvhoewihcdsgsdhlkghsdlgiwurghwrfbsldgkjsbgwrtugwpigbsldkgjdslgkdgl
        slfgkhslgusowiweuceouircnowefpweohwepoihfcnwepofcewncwpoirucenwfcpeoifcnewpofihewncpefo
        dshgsdlgsjdhglsdkjghdsvhoewihcdsgsdhlkghsdlgiwurghwrfbsldgkjsbgwrtugwpigbsldkgjdslgkdgl
        slfgkhslgusowiweuceouircnowefpweohwepoihfcnutfcewncwpoirucenwfcpeoifcnewpofihewncpefo
        dshgsdlgsjdhglsdkjghdsvhoewihcdsgsdhlkghsdlgiwurghwrfbsldgkjsbgwrtugwpigbsldkgjdslgkdgl
        slfgkhslgusowiweuceouircnowefpweohwepoihfcnwepofcewncwpoirucenwfcpeoifcnewpofihewncpefo
        dshgsdlgsjdhglsdkjghdsvhoewihcdsgsdhlkghsdlgiwurghwrfbsldgkjsbgwrtugwpigbsldkgjdslgkdgl
        slfgkhslgusowiweuceouircnowefpweohwepoihfcnwepofcewncwpoirucenwfcpeoifcnewpofihewncpefo
        dshgsdlgsjdhglsdkjghdsvhoewihcdsgsdhlkghsdlgiwurghwrfbsldgkjsbgwrtugwpigbsldkgjdslgkdgl
        slfgkhslgusowiweuceouircnowefpweohwepoihfcnutfcewncwpoirucenwfcpeoifcnewpofihewncpefo
        dshgsdlgsjdhglsdkjghdsvhoewihcdsgsdhlkghsdlgiwurghwrfbsldgkjsbgwrtugwpigbsldkgjdslgkdgl
        slfgkhslgusowiweuceouircnowefpweohwepoihfcnwepofcewncwpoirucenwfcpeoifcnewpofihewncpefo
        dshgsdlgsjdhglsdkjghdsvhoewihcdsgsdhlkghsdlgiwurghwrfbsldgkjsbgwrtugwpigbsldkgjdslgkdgl
        slfgkhslgusowiweuceouircnowefpweohwepoihfcnwepofcewncwpoirucenwfcpeoifcnewpofihewncpefo
        dshgsdlgsjdhglsdkjghdsvhoewihcdsgsdhlkghsdlgiwurghwrfbsldgkjsbgwrtugwpigbsldkgjdslgkdgl
        slfgkhslgusowiweuceouircnowefpweohwepoihfcnutfcewncwpoirucenwfcpeoifcnewpofihewncpefo
        dshgsdlgsjdhglsdkjghdsvhoewihcdsgsdhlkghsdlgiwurghwrfbsldgkjsbgwrtugwpigbsldkgjdslgkdgl
        slfgkhslgusowiweuceouircnowefpweohwepoihfcnwepofcewncwpoirucenwfcpeoifcnewpofihewncpefo
        dshgsdlgsjdhglsdkjghdsvhoewihcdsgsdhlkghsdlgiwurghwrfbsldgkjsbgwrtugwpigbsldkgjdslgkdgl
        slfgkhslgusowiweuceouircnowefpweohwepoihfcnwepofcewncwpoirucenwfcpeoifcnewpofihewncpefo
        dshgsdlgsjdhglsdkjghdsvhoewihcdsgsdhlkghsdlgiwurghwrfbsldgkjsbgwrtugwpigbsldkgjdslgkdgl
        slfgkhslgusowiweuceouircnowefpweohwepoihfcnutfcewncwpoirucenwfcpeoifcnewpofihewncpefo
        """ * 100 + "slfgkhslgusowiweuceouircnowblueohwepoihfcnutfcewncwpoirucenwfcpeoifcnewpo"
